version: "3"
services:
  mysql:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: app
      TZ: "Asia/Tokyo"
    ports:
      - "23306:3306"

